---
- name: test dcnm module
  hosts: localhost
  vars:
    api_info: &api_info
      baseurl: https://10.67.28.160/rest
      username: admin
      password: "C1sco123!!"
      verify: no
  tasks:
    - name: dcnm_facts
      dcnm_facts:
        <<: *api_info

    - name: output fabrics
      debug:
        msg: "Fabric name: {{ item.fabricName }}"
      loop: "{{ ansible_facts.dcnm_fabrics }}"

    - name: create/update VRF
      dcnm_vrf:
        <<: *api_info
        fabric_name: test
        vrf_name: MyVRF_50001
        vrf_template_config: 
          nveId: "1"
          vrfVlanId: "2"
          asn: "65500"
          vrfName: "MyVRF_50001"
          vrfSegmentId: "50001"
        vrf_id: 50001
        state: present